update

diff --git a/bootstrap/10-main b/bootstrap/10-main
--- a/bootstrap/10-main
+++ b/bootstrap/10-main
@@ -13,8 +13,12 @@ BREW_VERSION="1.3.6"
 LINUXBREW=$MYLOCAL/Linuxbrew
 ANYENV=$MYLOCAL/anyenv
 
-git submodule init
-git submodule update
+if which git >/dev/null 2>&1 ;then
+	git submodule init
+	git submodule update
+else
+	echo "git not found. Please run 10-main again after install git."
+fi
 
 if [[ ! -e "$MYLOCAL" ]];then
 	mkdir -p $MYLOCAL
@@ -24,14 +28,56 @@ fi
 #	ln -s $MYLOCAL ./local
 #fi
 
+if ! which git >/dev/null 2>&1;then
+		pushd $PWD
+			cd /tmp
+			if which curl >/dev/null 2>&1 ;then
+				curl -L https://github.com/git/git/archive/master.zip -o git.zip
+			elif which wget >/dev/null 2>&1 ;then
+				wget https://github.com/git/git/archive/master.zip -O /tmp/brew.zip
+			else
+				echo "curl or wget not found."
+			fi
+			unzip git.zip
+			cd git-master
+			make configure
+			./configure --prefix=$MYLOCAL --with-openssl
+			make -j4 all
+			make install
+			cd ..
+			rm git.zip
+			rm -rf git-master
+		popd
+fi
 if [[ ! -e "$LINUXBREW" ]];then
 	#git clone -b $BREW_VERSION --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
-	git clone --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
+
+	if which git >/dev/null 2>&1 ;then
+		git clone --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
+	elif which curl >/dev/null 2>&1 ;then
+		pushd $PWD
+		cd /tmp
+			curl -L https://github.com/Linuxbrew/brew/archive/master.zip -o /tmp/brew.zip
+			unzip /tmp/brew.zip
+			mv /tmp/brew-master $LINUXBREW
+		popd
+		rm /tmp/brew.zip
+	elif which wget >/dev/null 2>&1 ;then
+		pushd $PWD
+		cd /tmp
+			wget https://github.com/Linuxbrew/brew/archive/master.zip -O /tmp/brew.zip
+			unzip /tmp/brew.zip
+			mv /tmp/brew-master $LINUXBREW
+		popd
+		rm /tmp/brew.zip
+	else
+    echo "curl or wget not found."	
+	fi
 fi
 
-if [[ ! -e "$ANYENV" ]];then
-	git clone --depth 1 https://github.com/riywo/anyenv $ANYENV
-fi
+#if [[ ! -e "$ANYENV" ]];then
+#	git clone --depth 1 https://github.com/riywo/anyenv $ANYENV
+#fi
 
 #brew install git ruby git-lfs
 #export PATH=/home/local/python/anaconda3/bin:$PATH
@@ -63,6 +109,7 @@ touch ~/.zshrc.local
 #touch ~/.zprofile.local
 
 mkdir -p $MYLOCAL/usr/share/icons
+mkdir -p $MYLOCAL/usr/lib/locale
 mkdir -p $MYLOCAL/tmp
 mkdir -p $MYLOCAL/opt
 mkdir -p $MYLOCAL/lib
