udpate

diff --git a/bootstrap/10-main b/bootstrap/10-main
--- a/bootstrap/10-main
+++ b/bootstrap/10-main
@@ -13,12 +13,20 @@ BREW_VERSION="1.3.6"
 LINUXBREW=$MYLOCAL/Linuxbrew
 ANYENV=$MYLOCAL/anyenv
 
-if which git >/dev/null 2>&1 ;then
+if ! which curl >/dev/null 2>&1;then
+	$CTG/provision/Curl
+fi
+
+if ! which git >/dev/null 2>&1;then
+	$CTG/provision/Git
+fi
+
+#if which git >/dev/null 2>&1 ;then
 	git submodule init
 	git submodule update
-else
-	echo "git not found. Please run 10-main again after install git."
-fi
+#else
+#	echo "git not found. Please run 10-main again after install git."
+#fi
 
 if [[ ! -e "$MYLOCAL" ]];then
 	mkdir -p $MYLOCAL
@@ -28,27 +36,6 @@ fi
 #	ln -s $MYLOCAL ./local
 #fi
 
-if ! which git >/dev/null 2>&1;then
-		pushd $PWD
-			cd /tmp
-			if which curl >/dev/null 2>&1 ;then
-				curl -L https://github.com/git/git/archive/master.zip -o git.zip
-			elif which wget >/dev/null 2>&1 ;then
-				wget https://github.com/git/git/archive/master.zip -O /tmp/brew.zip
-			else
-				echo "curl or wget not found."
-			fi
-			unzip git.zip
-			cd git-master
-			make configure
-			./configure --prefix=$MYLOCAL --with-openssl
-			make -j4 all
-			make install
-			cd ..
-			rm git.zip
-			rm -rf git-master
-		popd
-fi
 if [[ ! -e "$LINUXBREW" ]];then
 	#git clone -b $BREW_VERSION --depth 1 https://github.com/Linuxbrew/brew $LINUXBREW
 
